<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rs_Title</name>
   <tag></tag>
   <elementGuidId>0d6b77a2-1465-49c5-8bba-bc9e791d5d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@class='ui-pdp-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filters__group filters__category </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_category</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Categorías    Placas de Video (4.804)       Motherboards (6.769)       Discos Rígidos y Removibles (20.871)       Memorias RAM (13.400)       Coolers y Ventiladores (10.937)       Procesadores (6.818)       Gabinetes de PC y Soportes (4.099)       Fuentes de Alimentación (4.070)       Placas de Sonido (2.434)    Ver todos     Elegir Categorías          Coolers y Ventiladores (10.937)       Discos Rígidos y Removibles (20.871)       Disketteras (323)       Editoras de Video (970)       Fuentes de Alimentación (4.070)       Gabinetes de PC y Soportes (4.099)       Lectoras Internas de Discos (34)       Memorias RAM (13.400)       Motherboards (6.769)       Placas Controladoras (1.615)       Placas de Sonido (2.434)       Placas de Video (4.804)       Placas USB y Firewire (782)       Procesadores (6.818)       Sintonizadoras de TV (374)       Zip Drives (68)       Otros (2.244)      </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_category&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//dl[@id='id_category']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inner-main']/aside/section[2]/dl[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1.193)'])[1]/following::dl[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solo tiendas oficiales'])[1]/following::dl[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dl[2]</value>
   </webElementXpaths>
</WebElementEntity>
